### ISSUE TITLE
Music Video Library Being Scanned

### ISSUE THREAD

**Issue by leejk421** [croneter/PlexKodiConnect#102]
It appears that PlexKodiConnect is trying to scan my music video library that I have setup in KODI. I tested this by disabling the add-on, starting KODI, and then looking at the log for the WARNING messages in the log about no information not being found for them. I have the music video library setup in KODI to use local information. It works fine. However, when PlexKodiConnect is enabled, it tries to scan this library on startup, and generates the WARNING entries in the log. Not sure why it would try and do this, unless it's confused since it doesn't exist in Plex. Here is my log: http://pastebin.com/1WMHCNXb

Also, a similar problem is noticed when scanning my music library, which is setup by KODI. For newly found songs, PlexKodiConnect tries to scan for it on the Plex server. Just noticed this tonight.

**Comment by croneter** [comment]
Your issue with warning of the type
```
09:52:45 T:5436   DEBUG: ADDON::CScraper::FindMovie: Searching for ''Til Tuesday - Voices Carry' using Local information only scraper (path: 'C:\Program Files (x86)\Kodi\addons\metadata.local', content: 'musicvideos', version: '1.0.0')
09:52:45 T:5436 WARNING: No information found for item 'nfs://192.168.0.101/volume2/video1/music videos/'Til Tuesday/'Til Tuesday - Voices Carry.m4v', it won't be added to the library.
```
are not in any way related to PKC. They are caused by the Kodi scrapper (`CScraper::FindMovie`) not finding any info/metadata for your music videos. See e.g. here: http://forum.kodi.tv/showthread.php?tid=288389. I would actually expect that for music videos, as there is not much metadata available for music videos in general. 

For the other matter: Use **either** PKC/Plex for music **or** Kodi directly - don't mix/combine the setup between the two!!

**Comment by leejk421** [comment]
Thank you.
