### ISSUE TITLE
Does PKC Sync Plex Smart Playlists with Kodi and update them when needed?

### ISSUE THREAD

**Issue by GOvEy1nw** [croneter/PlexKodiConnect#1193]
Originally, when using the original Plex app, I setup some simple collections in Plex so it's easier to navigate my movies. However, I do find collections annoying since I have to manually update them. 

Because of this, I was thinking of using Plex smart playlists instead, since I now use PKC with Kodi & can set the playlists up as widgets. Plex smart playlists  are more powerful than the kodi smart playlists too, which is why I'd rathe make them in Plex and then Sync to Kodi. But my question is whether the playlists will auto update in Kodi if the playlist auto updates in Plex based on the smart filtering?

Also, it seems artwork doesn't show up for the playlists synced from Plex to Kodi, is that normal?

**Comment by croneter** [comment]
I honestly don't know whether the playlists will update or not - try for yourself :wink:. It all depends on whether Plex sets a certain flag for a specific playlist or not.

Yes it's normal that artwork doesn't appear. This is caused by Kodi and how Kodi's playlists function (or not). You could, however, navigate to the PKC Kodi addon, then playlists - you'd get everything.
