### ISSUE TITLE
Direct Paths outside of my network

### ISSUE THREAD

**Issue by pszor** [croneter/PlexKodiConnect#1238]
Hello.

Is it possible to use "direct path" when accessing my sinology NAS outside of my network?
How can I configure PKC to work in this situation?

**Comment by croneter** [comment]
Yes you can use direct paths even when you're outside your LAN, but you'll need a VPN most probably. Your client will thus appear like it's part of the LAN. I don't know whether that's worth the hassle, though, since Addon Paths work fine in most cases...

No further support here though. Setting up a VPN, making sure that all necessary ports are open, etc., etc. is a PITA and not in scope of PlexKodiConnect-support 😉
