### ISSUE TITLE
I'm not able to set up Direct Paths to NAS with NFS

### ISSUE THREAD

**Issue by krzymn** [croneter/PlexKodiConnect#1244]
Hi,

It's not really a bug that I'm reporting, but I didn't know where else to comment.

I've just started to use PlexKodiConnect (it's great, thx a lot, I bought you a kofi btw!). I'm using it on Kodi on a "Fire TV Stick", and Plex server is installed on my Synology NAS. I would like to set up direct paths in NFS. I tried for hours but it didn't work. I don't know where I made a mistake. The wiki didn't help much. The reasons why I would like to do is that NFS direct paths would be faster and I'd have less playback delays I reckon.

This is what I did:
- In "Set Network credentials for direct paths and direct plays", I entered my NAS ip (something like 192.168.1.02), then "nfs" instead of "smb".
- Then what about the username / password? What is it referring to? I just entered "plex" as username and "plex" as password, not knowing what to do.
- Then I tried to "let PKC substitute paths". There were no examples for Synology NAS and NFS but I tried "volume1/Shared_Folder/Films" (where my movies are) and "nfs://192.168.1.02/volume1/Shared_Folder/Films"
- Then I did the other steps. When restarted kodi, it sayed somenthing like "Can't find /nfs://192.168.1.02/volume1/Shared_Folder/Films/Dune (1984)/Dune.avi. Stop syncing?"

I don't know what I did wrong, since there are many steps for which I'm unsure. Help would be much appreciated!

Thanks a lot!

**Comment by croneter** [comment]
Sorry, but my advice is simple here: do not use direct paths but add-on paths. I personally also use add-on paths. Since you don't even know which username and password the sink talks about, you haven't configured NFS on the server where your media resides

Sorry, no support here to configure direct path for a single user like you. I'd rather focus my energy on further developing pkc
