### ISSUE TITLE
Kodi 18 - Leia: Unsupported version of Kodi

### ISSUE THREAD

**Issue by m1ndf1r3** [croneter/PlexKodiConnect#148]
Hi great software thank you until now ive not had any issues with it.

I had to upgrade at Openelec 7 beta as they corrected the no samba share found error in the stable version 6 somehow this appears to have an impact on PKC, 

Upon installing PKC i am experiencing the following issues:
1. Plex media server not found, i have to enter the IP manually (not a problem but i remember it not being the case before i upgraded to OE7b).

2.once installed i get an error message stating database sync cancelled due to Kodi version not being supported.

3. if i try a manual sync, i get movies in the addon menu item within Kodi (no items are displayed on the kodi desktop) i do not get any TV Show entries in the same addon menu item even though the sync process seems to be scrobbling for them and no music (now i know the music feature is supposed to have problems anyway but it always found and managed my collection without huge errors before the update).

Long and short of it, at present im looking at buying a seperate RPi just for plex.. which is a shame because the app worked so well before.

What do you need from me, logs etc? and which ones/where to find them.

again love the software when i can get it to work :)

**Comment by croneter** [comment]
Kodi/Openelec Beta is called Beta for a reason, unfortunately. How things work might change overnight... This sounds like a LOT changed :-(

Logs would be a start, see here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Long story short: my recommendation is to **NOT** use PKC direct paths. You won't need smb shares. Then stick to a **stable LibreElec** version instead of an unstable OpenElec... I myself switched 4 months ago from OpenElec to LibreElec.

**Comment by m1ndf1r3** [comment]
I had to switch to openelec as the VPN managers on metalkettle's repo dont
work with Libre, every time I tried it showed the error "this is a console
based add-on"

And as for the samba shares one of the features of exodus is that you can
set download paths for tv and movies, without samba working you can't set
the download location to anything but the device Kodi is installed on (I
have a nice 6tb headless pc sat behind the tv cabinet which I use primarily
as a plex server)

**Comment by croneter** [comment]
Logs?

**Comment by m1ndf1r3** [comment]
sorry its taken a while... have to do things like this while my toddlers
isnt around https://paste.ubuntu.com/23558288/

**Comment by dettwild** [comment]
I may have figured this out (had similar issue with a nightly from Milhouse). Seems that Kodi labeling some late Alpha releases as Version 18 (rather than 17 - Krypton), but still on the same db versions as 17. Therefore it may fix the issue, if you add a line to "utils.py" around line 221. Putting "18":107 there resolved the issue for me ;-). 
@croneter: Thanks very much for all your work on the tool - I am loving how it brings together the best of both worlds. I guess adding the above mentioned fix to the code does not "cost" anything. Btw, what is your preferred method of communicating about PKC, e.g. with regards to suggestions or even feature proposals (I don't like the term 'request' as it sounds quite demanding while we have noting to demand really from someone that devotes a lot of time for this) - Forum (getting a bit long with over 100 pages), Issues on github (like this one here) or some other means like a chat (gitter, slack etc)? 
@m1ndf1r3 : I hope this temp fix also works for you. The file in question resides inside the kodi folder (location depends on system) and then /addons/plugin.video.plexkodiconnect/resources/lib/utils.py

**Comment by m1ndf1r3** [comment]
Dettwild thank you!! i shall clear any previous plex data as i think ive
made a bit of a cock up while clearing DB's i think i deleted an XML file
in my haste... ill do a fresh install on my Pi alternthe file you mentioned
and then install PKC... ill post the results.

Regards

M1ndf1r3

**Comment by troych** [comment]
Just changing utils.py wasn't enough, there are some more cases where the code asks for Kodi Version. I had the same problem today and fixed it up on my forked branch.

I don't think it's a good idea to open a pull request with everything so bleeding edge on the Kodi side (we don't even know the name of V18 yet) but for those who like to try it: https://github.com/troych/PlexKodiConnect/commit/54509919027fe9c6dbc903d69472fca2e6a7dbd8

**Comment by troych** [comment]
Still having some trouble with certain Artists in my MusicDB being in there up to 10 times, not sure where this goes wrong, works on my Kodi 17 Version on my PC, doesn't work properly on Kodi 18 in the living room. 

Tried copying the Kodi 17 MyMusic60.db to 18 just to see what happens, works for a short moment, then the PlexKodiConnect Music scan runs and I've got the doubling of Artists again.

**Comment by croneter** [comment]
Solved in https://github.com/croneter/PlexKodiConnect/commit/289690813a811e0d432d7a24d4c462223f99fb7c
