### ISSUE TITLE
New subtitles require a full sync in order to be shown in Kodi

### ISSUE THREAD

**Issue by Shasoosh** [croneter/PlexKodiConnect#1522]
If I add subtitles to my library I will need to do a full sync in order for the subtitles to be discoverable by Kodi. I couldn't find a way to manually sync so I need to restart Kodi every time I add a subtitles to a specific Movie. 

I'm using Radarr and Sonarr to add movies to my library and new Movies will be presented in Kodi (most of the time) without a full sync but subtitles (that are downloaded automatically right after the movie finishes downloading and placed inside the movie folder) will not be detected by Kodi, only after a restart.

Is there a way to overcome this? Can PKC update the library when new subtitles are detected the same way it updates the library when a new movie is detected?

**Comment by croneter** [comment]
If PKC does not pick up new/changed subtitles immediately, this is due to the Plex Media Server not telling anyone about this - nothing I can do, sorry 😞 . 

What you can do is increase the frequency for full syncs in the PKC settings under `Sync`. Standard frequency is every 60 minutes.  Or you could bind a Kodi widget or key to the PKC menu item `Perform manual library sync` (Add-ons -> Video Add-ons -> PlexKodiConnect). Or you could switch to [PKC Direct Paths](https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths-Explained); Kodi should then automatically pick up any subtitle files lying in the same folder automatically

**Comment by Shasoosh** [comment]
Thanks for your amazing work @croneter .

I'll check the Direct Paths route.

**Comment by Shasoosh** [comment]
I moved to Direct Paths and movies play fine. One question though, I've noticed that when playing a movie I no longer have the option to select the quality of the movie (4K, 1080P etc'). Is this capability lost when using Direct Paths?

**Comment by croneter** [comment]
You need to bring up the Kodi context menu, then Plex settings, then "Play via PMS". You should be prompted then...
