### ISSUE TITLE
I'm not able to install PKC using source. 

### ISSUE THREAD

**Issue by leonard4546** [croneter/PlexKodiConnect#1551]
Kodi Version: 18.5
OS: WIndows 10

I followed the guide. added new source and then clicked on install from zip. kodi freezing for sometime after clicking on newly added source and nothing happening after that.

Log: https://paste.kodi.tv/azusurozul.kodi

**Comment by croneter** [comment]
Get Kodi 18.9 and please try again

**Comment by croneter** [comment]
Appart from upgrading to the latest available 18.* version 18.9, you need to 
1. Install the PlexKodiConnect repository. NOTHING will happen once you've done that
2. Install PKC from that repo. PKC will start then

Since you're having issues with 1., grab the ZIP file for the PKC repo from here and simply install THAT file "from ZIP" as detailed in the PKC installation instructions. Then continue with 2.
* Kodi 18 Stable: https://croneter.github.io/pkc-source/repository.plexkodiconnect.Kodi-Leia.STABLE.zip
* Kodi 18 Beta Version: https://croneter.github.io/pkc-source/repository.plexkodiconnect.Kodi-Leia.BETA.zip
