### ISSUE TITLE
Not working on Fire TV Stick 4K

### ISSUE THREAD

**Issue by loadamasta** [croneter/PlexKodiConnect#1861]
Install via web directory. No error but add-on is not even starting. Can only be deinstallated. No chance to get to the configuration menu.

**Comment by ncdaol** [comment]
Did you install the addon after installing the repo?

**Comment by croneter** [comment]
@ncdaol asked the right question (thanks!! ❤️) You need to 
1. Install the PlexKodiConnect repository: https://github.com/croneter/PlexKodiConnect/wiki/Install-PKC-Repository
2. Install PlexKodiConnect itself: https://github.com/croneter/PlexKodiConnect/wiki/Install-PKC-from-PKC-Repo

Until we're hearing back from you differently, I assume that your issue is solved.
