### ISSUE TITLE
Automatic update of movie and episode rating?

### ISSUE THREAD

**Issue by fjordnode** [croneter/PlexKodiConnect#1921]
I use UpdateTool (https://github.com/mynttt/UpdateTool) to get up to date IMDB scores for all my media. Updatetool runs in a docker container and updates the scores of all my content every 12h.

The problem I have is that PKC does not update these scores unless I manually run <force update all content>.
Is there any way to automate this prcoess in PKC?
If not, I would honestly be fine if I could automatically run <force update all content> every night or somethig.

Thanks!

**Comment by croneter** [comment]
No, there's no way. If UpdateTool changes any rating, it should modify the video's `updatedAt` timestamp. This does not happen. Hence no way for PKC to pick up any changes - PKC asks the PMS what items changed since e.g. last evening; the PMS does NOT include items that were changed by UpdateTool. 

Sorry

**Comment by croneter** [comment]
This is closely linked to https://github.com/croneter/PlexKodiConnect/issues/1893
