### ISSUE TITLE
PKC doesn't work with latest Kodi 21 Omega builds

### ISSUE THREAD

**Issue by ValentinDragomir** [croneter/PlexKodiConnect#1939]
I'm trying to set up PKC (beta repository) with Kodi 21 Omega (latest builds) and I'm getting the following message:

"The current Kodi version is not supported by PKC..."

The main reason for using the Omega nightly builds would be the superior support for HDR10+/Dolby Vision on Android TV. I'm already using PKC with Kodi 20 Nexus and it works great.

I've included the log file.

Thanks in advance!
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/10945581/kodi.log)

**Comment by Shawn9347** [comment]
I noticed it too. Kodi 21 is a major improvement. I already tested it with dolby vision files and it works flawlessly.

**Comment by Mr-Lucas** [comment]
Hello.  I'm still receiving the "The current Kodi version is not supported by PKC..." error.  But I am attempting to use PlexKodiConnect with the nightly android builds located here - https://mirrors.kodi.tv/nightlies/android/arm/master/

These builds are needed on the Amazon firetv cube 3 to support audio passthrough.  Any chance you could look into this?

**Comment by Mr-Lucas** [comment]
For grins, I also tried Plex Kodi Connect with the 32bit version of the windows nighties located here -  https://mirrors.kodi.tv/nightlies/windows/win32/master/

same "not supported by PKC" message.

**Comment by Shawn9347** [comment]
I don't think PKC is compatible with kodi 21 yet. With kodi 20 is works perfectly.

**Comment by Mr-Lucas** [comment]
> I don't think PKC is compatible with kodi 21 yet. With kodi 20 is works perfectly.

Yeah, there is not "officially" supported yet.  But he has built in support with a disclaimer.  "Preliminary support for Kodi 21 Omega. Keep in mind that development for Omega has not even officially reached alpha stage - any issues you encounter are probably caused by that"

I just downloaded the non-nightly version of Omega, and PKC works.  So it looks like the nightlies builds of omega do not pass the "version" check built into PKC.
