### ISSUE TITLE
table streamdetails has no column named strhdrtype?

### ISSUE THREAD

**Issue by Fma15** [croneter/PlexKodiConnect#1964]
Sometimes when I'm watching a video this pops up

table streamdetails has no column named strhdrtype

It seems to also happen when plexkodiconnect tries to scan my library. Is there anyway to fix this? It's kind of distracting when I'm watching a video.

Also, would it be related to this problem I have:

https://github.com/croneter/PlexKodiConnect/issues/1963

**Comment by croneter** [comment]
Please share your DEBUG log file after this issue happens, see here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Yes, this seems the root cause for your other issue #1963

**Comment by Fma15** [comment]
Thanks for the reply! Here is the logs

https://pastebin.com/yfHzJrCE

I don't think my plex token should be in it since I never actually opened plexkodiconnect to reproduce the error. I search the logs anyway, and it didn't seem like any sensitive info was in there.

Also there are other ways to reproduce the error. If you want me to send you logs with the other way let me know.

**Comment by edianannink** [comment]
I encountered exactly the same bug with a fresh installation of Kodi 20.1 on PopOS.  I'm unable to sync my libraries so the addon is completely unusable for me.

**Comment by croneter** [comment]
Revert back to 3.7.1 for now. Sorry for the hassle, your Kodi database does not look like it's supposed to 😞

**Comment by Fma15** [comment]
I still wanted the skip credits feature to work and if I downgraded to 3.7.1 skip credits wouldn't be supported anymore. So instead I downgraded kodi back to 19.3 and its working perfectly now. That being said, how when I know its ok to go back to kodi 20.1?

**Comment by reconman** [comment]
@croneter Does installing 3.7.1 and then updating to 3.8.0 fix the issue or is 3.8.0 broken on some devices?

**Comment by loadamasta** [comment]
3.8.0. did not solve the issue. Plexkodiconnect is not working on Nexus 20.1 on Apple TV. So, I have to stay at Kodi 19 or try Emby if it has to be Nexus.

**Comment by reconman** [comment]
@loadamasta Uninstall PlexKodiConnect, then install 3.7.1 from the Versions button next to the Install button.

**Comment by loadamasta** [comment]
> @loadamasta Uninstall PlexKodiConnect, then install 3.7.1 from the Versions button next to the Install button.

That worked, thank you.

**Comment by Son-Typ** [comment]
I have looked through @Fma15's log and discovered a discrepancy between the video database versions reported by Kodi (`Running database version MyVideos121`) and PKC (`Kodi video database version: 119`). PKC seems to use the old database file that does not have the `strhdrtype` column. When upgrading, Kodi does not delete the old version. I have traced this back to the algorithm that tries to find the "HIGHEST available and supported database version for the current Kodi version":
https://github.com/croneter/PlexKodiConnect/blob/3d34ba41b779111e26c0452d033c66a096c80bd8/resources/lib/variables.py#L717-L724

Due to the break, the first found database version is selected. The list of supported database versions for the video database looks like this:
https://github.com/croneter/PlexKodiConnect/blob/3d34ba41b779111e26c0452d033c66a096c80bd8/resources/lib/variables.py#L108-L112

It is ordered in ascending order. Hence, it selects version `119`, if it exists. Previously, this list was ordered in descending order, e.g., for Kodi 18 Leia:
https://github.com/croneter/PlexKodiConnect/blob/4b4dc1afbf2545480c9328e17830a2c6f9cf551b/resources/lib/variables.py#L109

The comment in line 108 also claims that numbers should be decreasing.

For a hotfix, you can move the old database file (version 119) to some other place (or delete it).

**Comment by croneter** [comment]
Fixed in [3.8.1 for Kodi Matrix and beyond](https://github.com/croneter/PlexKodiConnect/releases/tag/3.8.1)
