### ISSUE TITLE
Auto Skip feature getting stuck/repeating on most episodes

### ISSUE THREAD

**Issue by leaderofthegooftroop** [croneter/PlexKodiConnect#2002]
I'm having an issue For me when auto skip feature is enabled it gets stuck studdering and repeating itself on the last second
of the skip on some episodes.

**Comment by croneter** [comment]
Could you kindly share some DEBUG log files where this behavior got recorded? See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by Fizznaps** [comment]
[trimmedkodi.log](https://github.com/croneter/PlexKodiConnect/files/14364638/trimmedkodi.log)

Assuming this user is talking about the same thing I have been struggling with since the wonderful addition of intro skipping, I have attached my log that includes from the time I press play to the time to clicking stop on the player.

If I had to guess, this is related to skipping to specific values (as Plex supports this) where Kodi uses key frames.  If the key frame is behind the line of where the addon is attempting to skip to, it will attempt to skip on a loop because it never actually meets the time Plex/the addon is looking for when skipping.  Just a guess though.

**Comment by Fizznaps** [comment]
@croneter Sorry for the double post, but I noticed this is still labeled as "log file needed".  Do you need any more information for the label to be removed?

**Comment by croneter** [comment]
@Fizznaps Please share the ENTIRE debug log, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

1. Enable debug logging
2. Restart Kodi
3. Make sure to capture the bug, try not to do anything else to clutter up the log
4. Share the log file, having redacted your tokens :wink: 

Thanks!

**Comment by Fizznaps** [comment]
I didn't realize I had left out something crucial.  Here it is again using the same method of removing information about my instance and token but leaving all else in tact.

If this isn't sufficient, now that I have set up Kodi again on my Windows machine to capture this again for you I would be glad to give it another shot.  The behavior is consistent between the Windows and Android client.

[redactedkodi.log](https://github.com/croneter/PlexKodiConnect/files/15397746/redactedkodi.log)

**Comment by croneter** [comment]
Fixed in PKC version 3.10.1
