### ISSUE TITLE
Better way to handle "Direct Path" feature 

### ISSUE THREAD

**Issue by chewyf5** [croneter/PlexKodiConnect#212]
Hi croneter,

thanks for your nice kodi addon. May be I found a better way to handle the "Direct Path" feature for your addon. On my plex server setup i use some sub folders (you mention this in your wiki as a no-go ;-)) 

<pre>
/media/data1/movies/hd/movie.mkv
/media/data1/movies/dvd/movie.mpeg
/media/data1/movies/ld/movie.avi
</pre>

I share the folder movies in my network. So it is reachable via:

`smb://server/movies`

You see, your way of substitution is not workable for me because it changes the path from 

<pre>
/media/data1/movies/hd/movie.mkv  ==> smb://server/movies/movie.mkv
</pre>

which is not working obversely. 

**Solution:**

Instead of reorganizing my media library I use the following "works for me" solution. I create the same path on my client where kodi is running and mount the samba share direct to this local path.

<pre>
mkdir -p /media/data1/movies
chown -R <myuser>:<mygroup> /media/data1/movies
mount -t cifs -o username=<smbuser>,uid=<uid of myuser>,gid=<gid of myuser> //server/movies /media/data1/movies
</pre>

So the path of the movies is the same than stored on plex side. After I disabled the path changing features ("Pfad ändern" option in German) and enabled direct path. Works as a charm for me. May be this is an other solution you can add to your wiki in the direct path chapter. 

**Limits:**

I use Linux on client and on server side. I think it will work the same way on a Mac and Linux solution. (I should be equal who is client and who is server ;-)).
Via the mklink and the subst command (if necessary) it should even work with a Windows-Windows solution. 
For a Linux-Windows (equal who is client or server) I don't think that my solution will work. 

Kind regards

ChewyF5

**Comment by croneter** [comment]
It seems to me that there's an obvious, easy way with the existing mechanism to replace your paths. This works because e.g. all your movies ultimately lie in `smb://server/movies`. 

1.) Turn OFF `Replace Plex UNC paths`
2.) Turn ON `Replace Plex paths /volume1/media or \\myserver\media with custom SMB paths smb://NAS/mystuff`
3.) Set `Original Plex MOVIE path to replace:` to `/media/data1/movies`
4.) Set `Replace Plex MOVIE with:` to `smb://server/movies`
5.) Make sure that you chose Direct Paths in the Sync tab at the very bottom
6.) Resync the library in the Advanced tab, then `Partial or full reset of Database and PKC` (in red), then hit YES, YES, NO

So anyway: how is this an issue?

**Comment by chewyf5** [comment]
Hi croneter,

This is NOT an issue. I posted it here to enhance your wiki. Its only an easy way to use the direct path feature without the path substitution. You may like to add my solution to your wiki. 

Kind regards
ChewyF5

**Comment by croneter** [comment]
You can do that yourself - the wiki is open to anyone :-). Thanks!
