### ISSUE TITLE
PKC isn't updating Kodi database when a file changes name anymore

### ISSUE THREAD

**Issue by nilbarc** [croneter/PlexKodiConnect#26]
Sonarr updates some of the episodes in my library with better/different versions (I prefer WEBDL for most of my content) when these become available after the initial HDTV rips.

When these are replaced in my library, the file location of the item in my Kodi library isn't updated with the new location in 1.1.6 as it was in previous versions. I've included the portion of my log below where Kodi fails to find the file that was previously marked HDTV but is in fact now a WEBDL. This is for two shows, I then manually force a library refresh, then try again. Additionally, I have tried resetting the local database to no avail.

`[removed log to de-clog issue]`

**Comment by croneter** [comment]
Thanks for reporting. Unfortunately, the log is impossible to read and I cannot copy-paste it anywhere because all line breaks got lost on the way. Could you please attach a file or paste it here: http://pastebin.com/ in the future?

So to recap, and let's be extremely precise:
* You **ONLY** changed the filename?
* Manually syncing your PKC DB did not help (```Perform manual library synch```)
* Resetting the Kodi DB did not help (```PKC settings -> Advanced -> Partial or full reset of DB```)

Did you tell Plex to rescan your library? Does playing this episode work from e.g. Android or iOS?

**Comment by nilbarc** [comment]
My apologies, I've only just seen how the log is presented.

The file is changed to a different quality, as a result the old one (HDTV) is deleted and a new one (WEBDL) is put in the folder. The episode play fine on any other client. I have tried both manually synchronising the library and fully resetting the local database. The file plays fine via Samba over my local network by using Kodi's file manager.

If you'd like me to recreate a specific set of circumstances or parameters to generate a log, please let me know.

**Comment by croneter** [comment]
OK, that's extremely weird. Please if you have the time and leisure, I'd be happy look at new logs. Thanks if you can also capture the successful and unsuccessful attempts at playing 

Please do enable debug logging in the PKC settings. Might help.

**Comment by nilbarc** [comment]
Of course, anything I can do to help. I'll try and get it up here via Pastebin over the weekend.

**Comment by nilbarc** [comment]
Okay, below is a link to a pastebin of the log (token redacted).

To clarify, I reset PKC again last night and performed a full database reset and library sync. This evening, I attempted to play SNL - the file of which had been updated earlier. The updated file failed to play (even after a library sync), but would play fine via the Kodi file manager.

[http://pastebin.com/UVka832j](http://pastebin.com/UVka832j)

**Comment by croneter** [comment]
Maybe 1.1.9 helpes? :-)

**Comment by croneter** [comment]
I could not replicate your issues. Updates of filenames are detected and synched on my setup. Is it solved on your side with >=1.1.9 as well?

**Comment by nilbarc** [comment]
Unfortunately not, no. I'm going to completely go back to original settings today and try from the start again. Will report back.

**Comment by croneter** [comment]
What's your status? If this is still an issue, I'd love to get my hands on your logs with debug logging enabled (in the PKC settings - advanced). I could then track the messages your PMS sends out if a file name gets changed.

**Comment by Odeni** [comment]
Same problem here on 1.1.11. Sonarr replaces the file, notifies Plex which updates correctly. PKC only updates if I reset the Kodi database (yes, no, no).

Relevant lines from log: [http://pastebin.com/xpiDSAQH](http://pastebin.com/xpiDSAQH)

**Comment by croneter** [comment]
Hmm, PMS reports an error. 
```
22:50:00 T:1444  NOTICE: PlexKodiConnect WebSocket -> process : Received message from PMS server: {u'_elementType': u'NotificationContainer', u'_children': [{u'_elementType': u'AutoUpdateNotification', u'state': u'error', u'version': u'', u'key': u''}], u'type': u'update.statechange', u'size': 1}
```
What happens if you manually change a filename? Same issues?

**Comment by Odeni** [comment]
Yes, same thing. Changed the filename manually and:

`21:44:51 T:6032  NOTICE: PlexKodiConnect WebSocket -> process : Received message from PMS server: {u'_elementType': u'NotificationContainer', u'_children': [{u'_elementType': u'AutoUpdateNotification', u'state': u'error', u'version': u'', u'key': u''}], u'type': u'update.statechange', u'size': 1}`

Plex server is running on FreeBSD 10.3 but no issues with other clients.

**Comment by croneter** [comment]
@nilbarc you get these errors from the PMS as well?

**Comment by Odeni** [comment]
Correct.

**Comment by croneter** [comment]
Until @nilbarc reports back - @Odeni, what does your PMS log tell you about this error? You might want to wait a couple of minutes, maybe the PMS will not pick up the filename immediately, which could cause the issues

**Comment by jsahlen** [comment]
Just wanted to chime in that I'm seeing the same issue, using the latest PKC. I'm using Direct Paths, and if a file which was previously in PMS's database is replaced with a new file (same episode, different filename), the PMS database is updated (e.g. playing the episode in the PMS Web UI works), but the entry in Kodi's database is still pointing to the old filename, so it won't play (even after manual sync, etc.)

I can post logs when I get home tonight (CET, so in 10–12 hours). I've also tried switching over to the Plugin method instead of Direct Paths, and I'll see if that makes a difference. Thanks for the best addition to my Plexified home in years!

**Comment by croneter** [comment]
I would love to get your detailed logs (enable debugging in PKC settings, advanced) for both PKC/Kodi as well as the PMS. I currently cannot replicate this bug :-(

**Comment by jsahlen** [comment]
I'm afraid I won't have time to get proper logs tonight – I'll try my best to do it tomorrow 👍

**Comment by jsahlen** [comment]
Ok so here are the relevant parts (I think!) of my logs for Kodi and PKC: https://gist.github.com/jsahlen/cb4f06b017f3420fee791caf46f85222

My demo episode is Orphan Black season 4, episode 4. What I did:

1. Set PKC playback mode to Direct paths (with replacements)
2. Reset database and resync
3. Show info in Kodi for Orphan Black S04E06 shows full `smb` path to the original filename (`Orphan.Black.S04E06.1080p.WEB-DL-MYFAKEGROUP`). Playing the episode works well.
4. Replace the original file with a different one (`Orphan.Black.S04E06.720p.HDTV-FAKEGROUP`)
5. Rescan TV Shows in Plex Media Server. It picks up on the new file, and seems to notify PKC. It looks like PKC refreshes metadata and artwork (see logs.)
6. Show info in Kodi for Orphan Black S04E06 still shows the path to the original file. Trying to play the episode fails with an error message from Kodi saying the file isn't available and asking to remove it from the database.

I also tried syncing manually, but there were no changes to sync (since PKC had already downloaded the updated metadata in step 5.)

I hope this helps somewhat!

**Comment by croneter** [comment]
Thanks! Darn, no error on the PMS side this time.

**Comment by mattsch** [comment]
I'm seeing the same behavior.  I did let Kodi delete the old filename and then it was picked up on a rescan, just not sure why it's failing to update the path in the first place.  Did a quick skim of the code last night and nothing jumped out at me...

**Comment by croneter** [comment]
This bug is really starting to get my nerves... I haven't managed to reproduce it, which is not good :-). 

Could you please try the following: for `Wait before sync new/changed PMS item`, increase the timing to at least 300 seconds. Maybe the xml Plex submits does not contain the correct filepath **yet**

**Comment by mattsch** [comment]
Yup, I can certainly try that once I'm back home later today.

**Comment by jsahlen** [comment]
I'll try that too!

**Comment by mattsch** [comment]
Changing the timeout didn't seem to help in my case, still ended up with the old path.  I even tried changing the poster (this was a movie) which did get updated but the path stayed the same.

**Comment by croneter** [comment]
I think I finally found the bugger! :-)

**Comment by mattsch** [comment]
Awesome!  Looks like we might need a change around line 1047 (along the lines of 1066) to update the path for tv shows as well. Or perhaps that should be broken into a function to handle paths for add and update?

**Comment by croneter** [comment]
Argh, missed TV shows, thanks for reminding me :-).
