### ISSUE TITLE
Smart Playlists created blank - not working

### ISSUE THREAD

**Issue by metallyca** [croneter/PlexKodiConnect#305]
Version 1.8.x appears to have broken the Smart Playlists that get created PKC for each Plex Library. The playlists get created but are completely blank.  Attempting to edit the Plex (x).xsp playlists returns nothing and the menu just disappears and trying to "Browse Into" only returns back to Videos -> Library.  I have reset the Kodi database multiple times and still have the same issue.  This happens on both devices that I run PKC with.

Downgraded to 1.7.7 and the playlists get created properly again.

OS - LibreELEC 8.0.2
Kodi 17.3

Kodi Log - https://pastebin.com/pNjZ1ndT

**Comment by croneter** [comment]
I'm a bit at a loss here as I cannot reproduce the issue and the log doesn't tell us anything meaningful either 😒 

Just to be clear here: the PKC smart playlists cannot be edited manually within Kodi or outside using an editor. They may also be blank, e.g. simply because there is nothing "On Deck". 

* Try completely deleting the folder `library` in the [Kodi userdata folder](http://kodi.wiki/view/userdata)
* Could you please navigate to several of these "empty" smart playlists (https://wiki.libreelec.tv/index.php?title=Accessing_LibreELEC) and copy-paste the content here in this issue? Please do that for both 1.7.7 and 1.8.x so I can compare the content

**Comment by metallyca** [comment]
I deleted "library" folder and rebooted with no change.

Contents of _Plex 1.xsp_ file under **\\CLIENT\Userdata\playlists\video**

**1.7.7**
`<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="tvshows">
	<name>Plex TV Shows</name>
	<match>all</match>
	<rule field="tag" operator="is">
		<value>TV Shows</value>
	</rule>
</smartplaylist>
`

**`1.8.x`**
No contents

**Comment by croneter** [comment]
That was a really silly bug...
