### ISSUE TITLE
Direct Paths: PKC SMB Error on Fire TV

### ISSUE THREAD

**Issue by cmo1234** [croneter/PlexKodiConnect#324]
I can't understand this direct paths setup. I have two PKC setups one on my Windows Laptop and the other on a Fire TV.

They are both setup identically, native paths but I let PKC make the changes and have added nothing manually. They both playback everything without issue. The only difference is when you add new content, only the Fire TV throws that error.

My content is stored on a Windows machine that acts purely as a server and my paths within Plex Server are setup as below:-
\192.168.0.69\d\Films
\192.168.0.69\d\TV
\192.168.0.69\d\Music

This is all as discussed in the forum thread

Log at link https://pastebin.com/4tvtmaCC

**Comment by croneter** [comment]
Thanks for sharing. Is this still an issue or did removing the additional video source help? (I think that's what you did 😉 ). 

If it's still an issue:
* I cannot see PKC adding anything, nor having issues with adding new Plex content. Please enable PKC debug logging (in the PKC settings under Advanced) and capture the issue again: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug
* I take it that you're sharing the Fire TV log since that's where you're having issues

**Comment by croneter** [comment]
Closing as issue is solved
