### ISSUE TITLE
Connection problems with plex.tv

### ISSUE THREAD

**Issue by TheSylus** [croneter/PlexKodiConnect#33]
Hi, I have connection problem to my PMS. Setting up PKC works fine (sync libary and playing files)

Next time it takes a long time to find the server and to connect with the right user. The libary is not synced anymore.

Manually reselecting the server in the settings helps to sync again.

Log is send in the forum.

PMS and Kodi are on the same PC (win10)

**Comment by croneter** [comment]
You're connecting via plex.tv. Plex.tv returns a "hash" for your or your friend's PMS that is used as an IP to connect to. If you reset/tinker/maybe even just restart that PMS, this hash changes and you won't be able to reach it anymore.

For some reason, plex.tv won't give you an error right away for this "missing" PMS but only if you start requesting more than just a connect. That's why PKC probably doesn't give you a "proper" error.

For now, kindly use the settings to reselect your PMS. This will refresh the IP and everything is fine. It should not happen to often, no?

**Comment by TheSylus** [comment]
Thx for the reply. I was a few days off. I think the porblem arises nearly every day, so  i reselect the server on every start up. It is no problem for the moment, but I hope there is a long time solution

**Comment by TheSylus** [comment]
Just a quick remark. The problem is still existing with 1.1.1
