### ISSUE TITLE
Version 1.8.18 Setup Process Broken

### ISSUE THREAD

**Issue by avelis26** [croneter/PlexKodiConnect#361]
Raspberry Pi 3 Model B
Raspbian Lite Stretch
Installed Kodi from repo.
Downloaded PKC zip and installed.
Installed PKC.
Plex.Tv/pin dialogue pops up with pin but then almost immediately other dialogues open too like server select and PKC settings... very annoying and hard to get through set up process successfully.

Advise no auto-setup of any kind... force the user to actually open and configure the add-on :)

**Comment by avelis26** [comment]
And OH MY DEAR GOD... PLEASE PLEASE PLEASE F^%$ING HAVE ALEXA OFF BY DEFAULT !!!

**Comment by croneter** [comment]
Language please....

Have you tried using https://libreelec.tv/ on Raspi? I've been using it for months, no issues whatsoever. 

Also, have you tried installing PKC several times or just once? :-) There is a Kodi bug where the add-on might get called 2x instead of only 1x; I included some sanity checks, but once in a while they don't work.

**Comment by croneter** [comment]
Any update here?

**Comment by croneter** [comment]
Sorry, no feedback no issue
