### ISSUE TITLE
PKC and Google drive

### ISSUE THREAD

**Issue by Qwatuz** [croneter/PlexKodiConnect#384]
Greetings, I seen in the FAQ 

https://github.com/croneter/PlexKodiConnect/wiki/faq#gdrive-google-drive-does-not-work-with-pkc

> Gdrive (Google Drive) does not work with PKC!

> Gdrive features a limit to the number of API calls PKC can make. After that, an API ban will block further inquiries and PKC/Plex will stop working correctly. As PKC communicates with a Plex server heavily on initial syncs, basically copying the entire metadata to Kodi, chances are that you'll reach this limit.

I would like to clarify a couple things if that's possible.

If Plex is installed on a remote server, which is connected to a Gdrive (via plexdrive).

Running PKC on a different server, would PKC pull the library data from the remote Plex servers Plex database or would it try and pull it via Gdrive through the remote Plex?

If that wasn't clear, I am wanting to know if a PKC install on a different server than the Plex install, can cause API issues with Gdrive.

Thanks!

**Comment by croneter** [comment]
Yes, installing PKC on a different client NOT directly involved with Gdrive can still cause API iswues

**Comment by Qwatuz** [comment]
Thanks for the swift reply @croneter 

I think a user of my server may be frequently scanning my Plex library and getting me banned from Gdrive, is there any way of tracking down which user is doing it? I was hoping you may have some tips.

I'm aware that I cannot ban PKC from being used (other than when playing an item) on my server, but finding the culprit would be more than enough!

Thanks!

**Comment by croneter** [comment]
@Qwatuz 
Ouch, that's no fun. Check your Plex Media Server log file (you might need to enable debug logging). PKC will announce itself the entire time as "PlexKodiConnect"; see if a Plex username is in the vicinity of these entries...

**Comment by Qwatuz** [comment]
@croneter Thanks for the reply. Unfortunately I see no mention of PlexKodiConnect in the logs even when manually scanning a library using PKC - with debug logging mode enabled.

From the logs during a library scan with PKC I see lots of this:

`Line 1545: Jan 06, 2018 21:59:26.997 [0x7fda6dffe700] DEBUG - Auth: authenticated user 1092497 as <USERNAME>
	Line 1546: Jan 06, 2018 21:59:26.998 [0x7fda693ff700] DEBUG - Request: [<IP>:49114 (WAN)] GET /library/metadata/26?includeRelated=0&includeExtras=1&includeReviews=1&checkFiles=0 (13 live) TLS Signed-in Token (<USERNAME>)`


But no way of checking which app is doing the library scans. 

I assume there is no way of rejecting any PKC scan requests?

Thanks again for your help!

**Comment by croneter** [comment]
Enable verbose logging for your Plex media server and then check the PMS
logs again. PKC authorizes as PKC :wink:

Unfortunately there is no way to stop a PKC client from accessing your PMS.
Plex assumes that you can trust your friends here...



Am 06.01.2018 22:22 schrieb "Qwatuz" <notifications@github.com>:

@croneter <https://github.com/croneter> Thanks for the reply. Unfortunately
I see no mention of PlexKodiConnect in the logs even when manually scanning
a library using PKC - with debug logging mode enabled.

From the logs during a library scan with PKC I see lots of this:

Line 1545: Jan 06, 2018 21:59:26.997 [0x7fda6dffe700] DEBUG - Auth:
authenticated user 1092497 as <USERNAME> Line 1546: Jan 06, 2018
21:59:26.998 [0x7fda693ff700] DEBUG - Request: [<IP>:49114 (WAN)] GET
/library/metadata/26?includeRelated=0&includeExtras=1&includeReviews=1&checkFiles=0
(13 live) TLS Signed-in Token (<USERNAME>)

But no way of checking which app is doing the library scans.

I assume there is no way of rejecting any PKC scan requests?

Thanks again for your help!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/croneter/PlexKodiConnect/issues/384#issuecomment-355778088>,
or mute the thread
