### ISSUE TITLE
Repo is empty when attempting to install on SPMC

### ISSUE THREAD

**Issue by knalbone** [croneter/PlexKodiConnect#390]
Trying to install the PKC add-on on SPMC 16.7-02 on my Nvidia Shield TV. Using Repo version 1.0.2. When I look in the repo no add-ons are available for Music, Video, or Picture add-ons. I have reset all data for SPMC and even uninstall and reinstalled on my Shield TV. Kodi works fine, just not SPMC.

**Comment by croneter** [comment]
Are you the one who also posted on the Plex forums? Just asking to get a
feeling for how many people are impacted by this...


Am 06.01.2018 20:17 schrieb "knalbone" <notifications@github.com>:

**Comment by knalbone** [comment]
I am not. Didn't even think to look there.

**Comment by croneter** [comment]
Darn, then there is a problem :-/. Kindly share your DEBUG logs please, see
the wiki here for a how to


Am 06.01.2018 20:20 schrieb "knalbone" <notifications@github.com>:

**Comment by croneter** [comment]
No idea what's going on, SPMC does not throw any error, unfortunately. Opened a new issue on the SPMC side, check here: https://github.com/koying/SPMC/issues/1156

**Comment by Sogarez** [comment]
Same here, SPMC or clean Jarvis install on android 4.4 and empty repo as a result

**Comment by hstamas** [comment]
This is also happening with the Emby repo so definitely something on SPMC end.

**Comment by vin047** [comment]
Had the same issue. Install the version 17 (Krypton) build, add-on shows up properly there: [https://github.com/koying/SPMC/issues/936](https://github.com/koying/SPMC/issues/936)

Think its due to the fact that SPMC is still on version 16 (Jarvis) - the event log shows that scripts.module.certifi isn't present, and attempting to [install certifi manually](http://mirrors.kodi.tv/addons/krypton/script.module.certifi/script.module.certifi-2017.07.27.1.zip) fails with incorrect python version (it expects 2.25.0).

**Comment by Skyrid3r** [comment]
Hopefully this can be fixed.. Nor stable or Beta builds appears to work. Installation of the rep went fine, just empty addons directories.

**Comment by croneter** [comment]
## Workaround
[Install PKC directly from ZIP file](https://github.com/croneter/PlexKodiConnect/wiki/Installation#manual-installation-not-recommended). You will need to use the stable version as PKC >=2.0.0 will not be compatible with Kodi 16 anymore. You do not need to install the 2 dependency add-ons

**Comment by eightsixeight** [comment]
same here.. had to uninstall emby not cant even reinstall it...
