### ISSUE TITLE
Library sync thread crashes

### ISSUE THREAD

**Issue by Sogarez** [croneter/PlexKodiConnect#391]
Yesterday my plexkodiconnect addon started to fail with error "Library sync thread has crashed. You should restart Kodi now. Please report this on the forum".

Clean install did not help. I use FTMC fork for android 4.4, tried SBMC and original Kodi Jarvis - same results. 

P.S. I'm not using mysql as database, just default kodi install

FTMC logs:
https://pastebin.com/H6cUv6Eu
[ftmc.log](https://github.com/croneter/PlexKodiConnect/files/1622142/ftmc.log)

**Comment by milnash** [comment]
Have the same issue thought it was due to huge library, but not sure anymore...

Use Windows 10 + Kodi 17.6

**Comment by croneter** [comment]
You're using FTMC, which I don't know. 
```
Starting Ftmc (16.2-31 Git:2017-09-07-b42e794-dirty). Platform: Android ARM 32-bit
NOTICE: Using Release Ftmc x32 build
```
The issue is a missing SQL table `tag`
```
OperationalError: no such table: tag
```
This means that FTMC is using a Kodi 18 (instead of Kodi 17), which is still an alpha version. A lot of stuff changes, e.g. this table was dropped from one day to the other. 

PKC does not yet support Kodi 18. If I have the time, I'll look into it. 

Workaround: use an older version of FTMC. You must have updated it when it stopped working
