### ISSUE TITLE
Process directory ... does not exist - skipping scan.

### ISSUE THREAD

**Issue by AllanMarcus** [croneter/PlexKodiConnect#397]
Hi. I just installed PKC only Mac. Plex server is Linux.

It seems to be working, except I get this message one and over in the log:

WARNING: Process directory 'https://192.168.0.1:32400/library/parts/100937/1404678826/' does not exist - skipping scan.

192.168.0.1 is my server's IP.

There is a message in Kodi that says "Loading media information from files" and it's moving so slow that I cannot tell if it's doing anything.

Media is set to Direct Play.
playback mode set to Native (Direct Paths)
Media plays fine. Movies, TV, and Music
Path substitutions are set

Any ideas? Thanks.

Also, I don't see a Debug mode in the PKC advanced mode.

**Comment by croneter** [comment]
This is caused by you using Addon Paths, not Direct Paths; see https://github.com/croneter/PlexKodiConnect/issues/14

Your direct paths are not working, because you did not reset the Kodi database. Try https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths again by starting with resetting the Kodi database: under Advanced, hit the red `Reset the Kodi database...`, then Yes, Yes, No. 

Please note that I do NOT support you configuring direct paths here on Github. Otherwise I'd be doing nothing else...

**Comment by AllanMarcus** [comment]
ok, thanks
