### ISSUE TITLE
Profile-Logoff takes extremely long once PKC is enabled

### ISSUE THREAD

**Issue by pannal** [croneter/PlexKodiConnect#442]
I haven't fully figured this one out yet, but it seems that when PKC is enabled and connected to a PMS on a multi profile kodi instance, logging the current kodi profile off takes up to 15 seconds on my Vero 4K.

Edit: I can add DEBUG logs later for that, I'm guessing one of the background services doesn't exit fast enough?

**Comment by croneter** [comment]
Just checked here with my installation. The logoff takes a couple of seconds, true. Checking the log, it is NOT PKC directly causing this behavior as all PKC threads are killed more or less instantly. The problem is the PKC image caching thread, which also terminates really fast - BUT image caching is done entirely by Kodi and is unfortunately not stopped. 

Nothing I can do here, sorry... 

However, this problem should not be an issue in "daily life" 
- if you have Kodi already running for a while, then decide to switch profiles. Image caching should already be completed by the time you do so
- PKC will have finished caching your images at some point, heavily reducing the number of images being cached on startup (it'll only look for missing stuff). 

# Workaround
If fast Kodi profile switching is a Must for you, you have to deactivate artwork caching in the PKC entirely.
