### ISSUE TITLE
Bug when flinging music

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#45]
Fling from plex webapp works if I select a single music title. If I select an Album or a Playlist it starts the first song in the list. If I select the second title from an album it plays the first. After the first it plays the second but I cant play it directly only if I select the title within the title section so that it is the only one in the list.

Plex android app is crashing when I connect to kodi a music title is currently playing.

**Comment by gentle9** [comment]
I think this is the part of the log where it shows that the playlist is selected correctly but that it selects first item (item 0) of the playlist instead of the item with the correct key. 

`PlexKodiConnect - Full sys.argv received: ['plugin://plugin.video.plexkodiconnect/', '3', "?mode=companion&arguments={'protocol': 'https', 'key': '/library/metadata/6270', 'address': 'xxx', 'port': '32400', 'token': 'xxx', 'containerKey': '/playQueues/84?own=1&window=200', 'offset': '0', 'machineIdentifier': 'xxx', 'commandID': '6'}"]
NOTICE: PlexKodiConnect - Parameter string: ?mode=companion&arguments={'protocol': 'https', 'key': '/library/metadata/6270', 'address': 'xxx', 'port': '32400', 'token': 'xxx', 'containerKey': '/playQueues/84?own=1&window=200', 'offset': '0', 'machineIdentifier': 'xxx', 'commandID': '6'}
NOTICE: PlexKodiConnect entrypoint -> Playing a playQueue. Query was: {'window': ['200'], 'own': ['1']}
...
NOTICE: PlexKodiConnect Playlist -> ---*** PLAY ALL ***---
NOTICE: PlexKodiConnect Playlist -> Items: ['6278', '6267', '6265', '6269', '6268', '6271', '6270', '6272', '6273', '6275', '6274', '6276', '6279', '6281', '6280', '6283', '6282', '6284', '6285', '6286', '6287', '6288', '6289', '6290', '6301', '6303', '6300'] and start at: 0`

Another thing I like to mention is that the previous/next buttons on the plex webapp is triggering a rewind/forward instead of previous/next.

**Comment by croneter** [comment]
Should be solved in PKC beta (install from a dedicated PKC beta repository). Let me know if this is not the case
