### ISSUE TITLE
Kodi Leia: playback problems with 2.0.19

### ISSUE THREAD

**Issue by since85** [croneter/PlexKodiConnect#455]
i have problems with playing vom plex-server

many plays with error, and when ne tvshow run Tautulli dont show it nothing....

i have a log

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1934828/kodi.log)

**Comment by croneter** [comment]
I might have found a fix, but let me just warn you: there is a LOT changing on the Kodi Leia side. Many things have been broken, more will yet be broken.

With the latest nightly, for example, playstate updates of PKC don't work because kodi doesn't tell the correct player id. I can't and won't work around all those shortcomings...

In a nutshell - you are better of using Kodi Krypton :wink:

**Comment by since85** [comment]
i need Kodi 18 because of inputstream for netflix sky dazn ;)
