### ISSUE TITLE
Problem open subtitle file when transcoding

### ISSUE THREAD

**Issue by acidtracks** [croneter/PlexKodiConnect#465]
Hi,
I encounter an issue when i  try to read a transcode video. The issue is with french subtitles, PKC download a file in is temp directory named subtitle.Francais.srt. 
And when he try to read this file he search for subtitle.Français.srt with special char wich is cause this issue. 
When i rename the file with the special char it worked.

I attached the log to help
<REMOVED by @croneter because tokens were included>

**Comment by croneter** [comment]
Unfortunately, you did not follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug and replace your Plex tokens. I did remove your log file, however, the internet never forgets. 

Please **IMMEDIATELY** follow [I published my Plex token to some forum or Github. Anyone can now access my Plex Server!](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server) so that others cannot access your media!

**Comment by croneter** [comment]
Please use the latest beta version (>= 2.0.22) or wait until I push a new stable version (should happen in the next couple of weeks!). 

I already fixed this issue by naming all subtitles `subtitle.fr.srt` instead of `subtitle.Français.srt` :laughing:
