### ISSUE TITLE
Cannot sync to local server using .direct uri if not Internet connection

### ISSUE THREAD

**Issue by tomzini** [croneter/PlexKodiConnect#478]
Starting from versione 2.0.24 (with the introduction of .dirct uri) is no possible syncing to local LAN PMS when not internet connection is available.
The only workaround is to force the .dirct uri to be resolved using local 'hosts' configuration

**Comment by Lou-Cipher** [comment]
I agree this is a significant problem. I personally already maintain my own internal dns, but most people don't/don't know how/don't want to. Plus, I believe the direct uri is subject to change if you log your server out from and back into your plex account. Does pkc handle that scenario to update the url for the server?

I'd propose this as a (possible) workaround: Allow the user to configure a "backup" IP, to be tried if the plex.direct url is unresolvable (in this case because of a lack of internet access), and if the backup IP is used, pkc will simply refrain from trying to sync artwork until it has a working direct url again (or, alternately, use of the backup IP could allow you to disable cert verification in curl calls. Less secure, but fully functional).

It's not the prettiest solution, but it would work to maintain pkc's functionality in an offline environment, without requiring users to maintain their own dns records.

**Comment by croneter** [comment]
Agreed, this is a problem. Working on it...

@Lou-Cipher 
> could allow you to disable cert verification in curl calls.
How do you see this happening? It's Kodi doing curl calls, I don't see a way for PKC to influence this. Nor a normal user "hacking his system" to achieve this, either

**Comment by croneter** [comment]
Also, what's the exact use case here? If you originally connected to your PMS while having internet access, then Kodi went offline, PKC will automatically pick up on the local IP. 

An interrupted artwork sync (by Kodi going offline) won't be fixable - PKC already saved "online" artwork urls (....plex.direct:32400/... and e.g. ...fanart.tv...). Kodi is doing the caching. 

I find this to be a "fringe case" really...

**Comment by tomzini** [comment]
from my side it's ok
