### ISSUE TITLE
PlexKodiConnect: selecting movie in search results does not show "resume from..." dialog box

### ISSUE THREAD

**Issue by bartplessers** [croneter/PlexKodiConnect#51]
Hello,
running latest versions of Kodi and PKC. of @croneter 
I noticed that when I search for a movie and click on it in the search results, the movie instantly resumes, without asking me to resume or restart. This is annoying if you want to restart the movie.
Can this be resolved in a next release?
thanx
B

**Comment by croneter** [comment]
Just to tell you - this bug is giving me major headaches. Kodi KNOWS that the respective item has a resume point. It should ask you whether you'd like to resume as soon as you select it. For some reason Kodi does not do that. 

Thing is that PKC is not involved at all in this process up until the movie has already started playing. Especially if you chose direct paths. 

Low prio for now, sorry...

**Comment by bartplessers** [comment]
ok, no problem.
It's just that a lot of apps are build on search those days. If you have large collections, it's the only way to navigate fast to a node. It's what made google big. So it's my preferred entrance, but I understand you can't control everything in KODI.
Anyway: thanx for taking a look at this. Keep up the good work!

**Comment by croneter** [comment]
Should be fixed with new PKC version 2.0.4. Let me know here if this should not be the case.
