### ISSUE TITLE
Music tab not syncing

### ISSUE THREAD

**Issue by jbowwow02** [croneter/PlexKodiConnect#529]
During the library sync the music tab does not get updated with new library entries (recently added). Additionally this process seems to prevent kodi from shutting down and continues on when trying to close the app.
I believe the music sync spam issue is the same as the one that is already known but the real problem is the shutdown as it requires me to restart my fire tv everytime if I want to restart the app.

[pkc_log.log](https://github.com/croneter/PlexKodiConnect/files/2305160/pkc_log.log)

**Comment by croneter** [comment]
There's 2 issues here:

## 1) Kodi not shutting down
This is due to the fact that you're using add-on paths **AND** chose to sync Plex music, see issue https://github.com/croneter/PlexKodiConnect/issues/14. Kodi (and not PKC) keeps unsuccessfully scanning the music library and thus won't shut down properly. There is no way for PKC around this, except [switching to direct paths](https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths-Explained) or killing the Kodi application manually. 

## 2) The Kodi music tab does not get updated after a PKC library sync
Please elaborate here. What exactly does not get updated? A screenshow would help

**Comment by croneter** [comment]
> I actually removed my music library and reset PKC yesterday after I realised it was probably just because my library was too damn big and I am unable to use direct paths because of the fire stick's limited hardware capabilities. 

Just that you know, direct paths do NOT make any difference here. If anything limits the fire stick, it's caching artwork (can be deactivated in the PKC settings under `Artwork`). 

Thanks for reporting back
