### ISSUE TITLE
Photos from plex not showing at Kodi library

### ISSUE THREAD

**Issue by eskimos2000** [croneter/PlexKodiConnect#547]
Hi,

Again Xbox one S, Kodi Leia beta 3 and everything working but photos from plex photo library not showing at Kodi Photos tab. What to do?

**Comment by croneter** [comment]
Sorry for the delay, Fotos are a bit of a pain... Does it work if you navigate to the Kodi picture section, then Picture Addons, then PlexKodiConnect?

Pictures are not synced like e.g. movies but just linked to. Also, Kodi forces you to navigate to the picture section first, otherwise it won't work (guess because Kodi expects videos...).

**Comment by eskimos2000** [comment]
Yeah it works as you described so I can get them watch somehow. A few more clicks so can live with that ;-). Can I somehow turn of pictures like music from add-on and use Kodi directly to watch them ?

**Comment by croneter** [comment]
You can make a shortcut on your Kodi homescreen linking directly to your photos. Just be sure that you navigate via Photos - Photo Addons! See https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins

I don't understand why you would want to turn anything off regarding photos? There is nothing actively done by PKC anyway

**Comment by eskimos2000** [comment]
Oh, I forgot about such a thing like nodes, that solves all my problem, thx.
