### ISSUE TITLE
Newly added is missing poster/artwork

### ISSUE THREAD

**Issue by coz2001** [croneter/PlexKodiConnect#602]
The title says it all.

2.5.13 & RC4

**Comment by croneter** [comment]
In the PKC settings under Artwork, activate the first option. Then reset the database under Advanced.

**Comment by coz2001** [comment]
It is activated I never deactivated it, I will try to toggle the option and reset database then.

**Comment by croneter** [comment]
Please enable debug logging, then Reset the database again, share log

**Comment by coz2001** [comment]
Thanks for getting back, I tried so many resets downgraded PKC updated PKC and can't get any artwork to load, what I didn't try was to reset PKC settings but would prefer not to though if possible.

Anyway here are logs before and after the database reset hope you can find something useful.

[Before restart.log](https://github.com/croneter/PlexKodiConnect/files/2751757/Before.restart.log)

[After restart.log](https://github.com/croneter/PlexKodiConnect/files/2751758/After.restart.log)

**Comment by sarbian** [comment]
I had a similar problem. It turns out that my plex.direct address changed (when the cert needed to be renewed) and PlexKodiConnect was still using the old one. The plex server replied with a certificate for the new address and it generated certificate errors. 
I selected plex server again on the config (Settings, Connection, Choose from a list) and it fixed everything.

**Comment by coz2001** [comment]
Thanks sarbian, I tried your suggestion and it didn't work, but I do believe you are right about the cert stuff cause what did work was reset PKC settings and sign in to Plex again, so the artwork is back now.
