### ISSUE TITLE
Create new PKC setting to optionally choose language code, not string for synching

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#61]

**Comment by bartolomesoriano** [comment]
As mentioned in the forum, any playlists based on audio language or subtitle language code (which is how Kodi normally stores this) will not be populated correctly.

Also, since Plex uses the full name in the original language (meaning PKC will write Español instead of Spanish in the Kodi db), the non-standard characters like ñ will make certain addons fail, like script.skin.info.service, when they parse the details for a movie or a tv episode.
