### ISSUE TITLE
Problem when activate/deactivate passthrough option during playback

### ISSUE THREAD

**Issue by rmellid** [croneter/PlexKodiConnect#971]
Hello,
I found a problem when I activate or deactivate the option "Allow passthrough" during playback.
Normally, when I change this option, the media is paused 2-3 seconds and then continue. But with PKC, the media restart on the penultimate time. 
If I watch the media for the first time, the media restart from the beginning after changing this option.
![img_passthrough](https://user-images.githubusercontent.com/53934742/62966848-2d44a500-be08-11e9-8f1e-ee3bb94d229b.png)
[kodi_passthrough.log](https://github.com/croneter/PlexKodiConnect/files/3498338/kodi_passthrough.log)

**Comment by rmellid** [comment]
Hello Croneter,
did you find something about this problem ?

**Comment by V33m** [comment]
Audio settings should only be set / changed in "Settings" -> "System" -> "Audio". There shouldn't be any need for changing audio settings during playback. Take a look here: https://kodi.wiki/view/Audio_quickstart_guide

This shouldn't be necessary to look into for Croneter and can be closed

**Comment by croneter** [comment]
Nice! Thanks for the info @V33m !

**Comment by rmellid** [comment]
@V33m 
I reported a bug about an official kodi function  that don't works fine with PKC. 
your response: don't use this function....    so funny...
FYI, this option is very useful for many users when your audio decoder is not compatible with all format. 
I known it s not a main problem, but I think  the project would be better with a maximum of bug corrected.

**Comment by V33m** [comment]
The reason why isn't that changing audio settings during playback is problematic, but that you have not setup your audio settings correctly in the beginning. If you had setup everything correctly, you would not need to change audio settings during playback... And I speak of years with experience with different AVRs and LibreELEC/CoreELEC!

And no, the project would not be better off with "maximum bug corrected" and the reason for that is time constraints. Croneter doesn't have time to look into features and bugs which minor people are facing. And especially not problems/bugs which are caused because end-users have not setup their system correctly...

So to help you in this regard, please give me all information about your system, build, setup etc. I good starting point is to revert to default settings and then look into the Kodi Audio guide I posted.
