### ISSUE TITLE
Multiple Plex users with multiple Kodi profiles: Kodi crashes

### ISSUE THREAD

**Issue by harvestnide** [croneter/PlexKodiConnect#973]
Hi. Is this [instruction](https://github.com/croneter/PlexKodiConnect/wiki/Several-Plex-Users) apply only to Plex home users? I tried to do this with two separate accounts (i don't have pass right now) and second user just doesn't work at all. When I press 'Sign out' on PKC menu Kodi think for few minutes, and then crash. Same when I tried to do this through PKC settings

**Comment by croneter** [comment]
Yes that also applies for several Plex accounts. Please share your DEBUG log of Kodi crashing https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by luisvillalobos528** [comment]
Hi, I'm having a problem like this let me try to explain. I have plexpass and in my setup I have 2 users, user A that is the primary user of plex ( Access to Movies and TV-Shows ) and User B that only has access to TV-Shows, both of those are Pin protected with different password, so I have 2 TV with a Chromebox with Kodi + PKC. I have user A in one tv and user B for the other tv, the problem is when I set up  the second TV the databases get mixed up, The watched status of User B gets mirrored to User A. I have done clean install of everything 3 times now and same issue arise.  I did notice that this started happening when I installed an update to Plex Server like 4 days ago. Let me know what should I do, which log you want me to attach, because even If I open the User A on the plex server machine all the statuses are wrong.

**Comment by croneter** [comment]
@luisvillalobos528 that seems to be a completely different issue. Please open a new issue here on github and copy paste your info. Please share your DEBUG log of BOTH machines after you've played something and the play status was wrongly synced to the other machine

**Comment by croneter** [comment]
@harvestnide no logs no help possible. Please share your Kodi log

**Comment by harvestnide** [comment]
Sorry, wasn't around for few days, now trying for replicate bug on clean Kodi installation, but for some weird reason PKC doesn't work at all. I'm reinstalling OSMC now

**Comment by harvestnide** [comment]
Migrated from OSMC to LibreELEC, now it's all working. Sorry for bothering..
