### ISSUE TITLE
Kodi crashes when casting from Plex to PKC

### ISSUE THREAD

**Issue by jackyaz** [croneter/PlexKodiConnect#995]
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
When casting, Kodi crashes immediately
```
terminate called after throwing an instance of 'std::logic_error'
```
seems to be printed to the log

## To Reproduce
1. Open Plex Web or Plex on Windows
2. Click on Cast and select PKC
3. Start a movie/tv show

## Expected behavior
Movie/tv show to start playing in Kodi

## You need to attach a KODI LOG FILE!
Log to follow

**Comment by jackyaz** [comment]
Log will be attached after re-sync following a 2nd reset is complete

**Comment by croneter** [comment]
Logs please :wink:

**Comment by jackyaz** [comment]
Should have later, Kodi is in use :(

**Comment by jackyaz** [comment]
Logs: https://www.dropbox.com/s/l9slfc4w4diz9hr/kodi.zip?dl=0

**Comment by croneter** [comment]
I did not find `terminate called after throwing an instance of 'std::logic_error'` in your logs. I don't find anything suspicious in either log from a PKC side. 

Kodi seems to be crashing when it's calling the PKC helper add-on for TV shows:
```
DEBUG: CPythonInvoker(5, /home/osmc/.kodi/addons/plugin.video.plexkodiconnect.tvshows/default.py): start processing
```
Does Kodi also crash for movies?
Did you try completely resetting Kodi ("factory reset")?

**Comment by jackyaz** [comment]
It does crash for movies too. I think I found that log line in the system's journal logging, I'll check if reproducible.

I reset Kodi's db via PKC but haven't gone beyond that yet.

Is there a way I can manually invoke the helper addon to see if that causes the crash?

Thanks for looking into this!

**Comment by croneter** [comment]
If you're using add-on paths, it'll be invoked every single time you start playing a video

**Comment by jackyaz** [comment]
Yes I am using addon paths. I didn't know if I could call at the command line to check for any errors dumped to the console

**Comment by jackyaz** [comment]
I'll also try a fresh install of Kodi

**Comment by jackyaz** [comment]
Haven't had a chance to reinstall OSMC (Kodi) as yet

**Comment by peacey** [comment]
I also experienced this same bug with Kodi crashing when I try to cast from Plex Web. Kodi doesn't crash if I cast from Plex app on Android (it casts successfully), but it does crash when trying to cast from Plex Web and Plex Desktop App (on Mac OS X). See attached log [kodi.log](https://github.com/croneter/PlexKodiConnect/files/3727596/kodi.log).

I don't see anything in the log about why it crashed, but I noticed that plex_companion is getting called twice for a single cast event, and the second time it says "Update for existing playqueue detected". However, if I cast from the Android app instead, I notice plex_companion only gets called once in the logs. I'm not sure why this behaviour happens for Plex Web or Desktop app, but I looked at the code in PKC plex_companion.py and in the if block where it checks if it's the same playqueue id (line 57), I added a "return" statement at line 62 in the if block to stop further execution the second time around. This fixed the issue of Kodi crashing and now I am able to cast from Plex Web and the Desktop App (and mobile still works), however I don't know the full implications of this change. I see from the comments in the if block that this block is only supposed to be called if a Plex companion reconnects, but in this case, it's happening not because of a reconnection (?), and that is possibly screwing something up in your code further down. 

Either way, I think that's where you have to look to figure out what's happening. The workaround I proposed fixes it and I don't notice anything else is broken, but I'm sure there is some unintended consequence to that hack since that if block is obviously there for some special reason.

**Comment by jackyaz** [comment]
This also seems to fix it for me! Since it seems to be in the plexcompanion.py, I don't think this will affect other usage of PKC? I rarely use the casting part, it's normally when I'm too lazy to navigate with the Kodi remote haha

**Comment by croneter** [comment]
Try PKC beta version 2.9.12 - should work now

**Comment by croneter** [comment]
Is this still an issue with PKC 2.10.0?

**Comment by croneter** [comment]
Guess not - let me know here if Kodi still crashes
